node:
  image: node:0.12-wheezy
  working_dir: /usr/src/app
  links:
    - hipache:redis
  volumes:
    - .:/usr/src/app
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - DOCKER_SOCKET=/var/run/docker.sock

node010:
  image: node:0.10-wheezy
  working_dir: /usr/src/app
  links:
    - hipache:redis
  volumes:
    - .:/usr/src/app
    - /var/run/docker.sock:/var/run/docker.sock

hipache:
  image: hipache
